{% set name = "umetrix" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/umetrix-{{ version }}.tar.gz
  sha256: b79e7812246e4a4c10cf13a77eeed607c8a52969cfb224d48c7a5f15e222234e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-scm
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.8
    - scikit-learn
    - scikit-image >=0.20.0

test:
  imports:
    - umetrix
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/umetrix
  summary: UNet Segmentation Metrics
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - goanpeca
